---
- name: manage package on linux machine
  hosts: all 
  become: true
  gather_facts: true
 
  tasks:
    - name: apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: remove package on linux customer machine
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ remove_packages }}"
      tags: remove
