all:
  children:
    #servers:
      #hosts:
       # servers1:
         # ansible_host: 192.168.9.110
         # ansible_port: 2222
         # ansible_user: gitea
         # ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    clients:
      hosts:
        abstract:
          ansible_host: 192.168.9.132
          ansible_port: 22
          #ansible_user: abstract

        marco1:
          ansible_host: 192.168.9.133
          ansible_port: 22
          #ansible_user: marco1
    
    #local:
      #hosts:
        #localhost:
          #ansible_connection: local    
        
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
